apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "breast_cancer.fullname" . }}
  labels:
    {{- include "breast_cancer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "breast_cancer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "breast_cancer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "breast_cancer.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.api.port.name }}
              containerPort: {{ .Values.api.port.number }}
              protocol: {{ .Values.api.port.protocol }}
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- range $name, $value := .Values.api.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.secrets.create }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
