{{- if .Values.mongo.secrets.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.mongo.secrets.name }}
data:
  {{- range $key, $value := .Values.mongo.secrets.values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}