apiVersion: v1
kind: Service
metadata:
  name: {{ include "breast_cancer.mongo.fullname" . }}
  labels:
    {{- include "breast_cancer.mongo.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "breast_cancer.mongo.selectorLabels" . | nindent 4 }}
